---
- name: Create directory structure
  file:
    path: "{{ directory }}"
    state: directory
    owner: "{{ musicplayer_owner }}"
    group: "{{ musicplayer_group }}"
  loop:
    - "{{ tracks_directory }}"
    - "{{ scripts_directory }}"
    - "{{ logs_directory }}"
  loop_control:
    loop_var: directory

- name: Copy helper scripts
  copy:
    src: "{{ script }}"
    dest: "{{ scripts_directory }}/{{ script }}"
    owner: "{{ musicplayer_owner }}"
    group: "{{ musicplayer_group }}"
  loop:
    - musicStop.sh
    - musicStart.sh
  loop_control:
    loop_var: script

- name: Copy MPD configuration
  copy:
    src: mpd.conf
    dest: /etc/mpd.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  become_user: root

- name: Add music start to rc.local
  lineinfile:
    dest: /etc/rc.local
    line: "mpc play"
  become: yes
  become_user: root

- name: Add aliases to bashrc for {{ musicplayer_owner }}
  blockinfile:
    block: |
      alias musicstop="{{ scripts_directory }}/musicStop.sh"
      alias musicstart="{{ scripts_directory }}/musicStart.sh"
    state: present
    path: "/home/{{ musicplayer_owner }}/.bashrc"
